stages:
- stage: stage1
  jobs:
  - job: Job1
    timeoutInMinutes: 2
    cancelTimeoutInMinutes: 2

    pool:
      name: 'Default'

    steps:
      - task: PublishBuildArtifacts@1
        displayName: Publish TestFolder
        inputs:
          pathToPublish: testFolder
          artifactName: Artifact1

      - task: PublishBuildArtifacts@1
        displayName: Publish yml
        inputs: 
          pathToPublish: azure-pipelines.yml
          artifactName: Artifact2
  
  
  - job: Download_all_by_default
    displayName: Download all artifacts by default
    dependsOn: Job1
    pool:
      name: 'Default'
    steps:
      - script: echo Will download all artifacts uploaded in Job1

- stage: stage2
  dependsOn: stage1
  jobs:
    - job: MyJobFromStage2
      displayName: download all artifacts from stage1 jobs
      pool:
        name: 'Default'
      steps:
        - script: echo I am stage2 Job

- stage: stage3
  jobs:
    - job: MyJobFromStage3
      displayName: don't download any artifacts from stage1 jobs as there is no dependency
      pool:
        name: 'Default'
      steps:
        - script: echo I am stage3 Job



      #- downloadArtifact:
      #  name: Artifact2
      #- task: PublishBuildArtifacts@1
      #  displayName: Publish NewTestFolder
      #  inputs:
      #    pathToPublish: NewTestFolder
      #    artifactName: NewTestFolder
